[project]
name = "interp"
version = "0.1.0"
description = "Auxiliar para interpolação de lagrange"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.1",
    "numpy>=2.2.4",
    "sympy>=1.13.3",
]
